### ISSUE TITLE
[InputTime] Remove margin-right on minutes using 24-hour setting

### ISSUE THREAD

**Issue by stevemdixon** [bufferapp/buffer-components#108]
`marginRight` is applied to each `select` element within `InputTime`. This feels smooth for the 12-hour state as the AM/PM `select` doesn't have `marginRight`. I'm curious if we can apply this same behavior to the 24-hour state as we're seeing a slight misalignment when centering `InputTime`.

**With `marginRight` on minutes:**

<img width="126" alt="screen shot 2017-06-15 at 12 19 38 pm" src="https://user-images.githubusercontent.com/1685602/27190966-3429f5ba-51ee-11e7-9800-81f4129da88a.png">

**Without `marginRight` on minutes:**

<img width="142" alt="screen shot 2017-06-15 at 12 19 47 pm" src="https://user-images.githubusercontent.com/1685602/27190988-4a33955a-51ee-11e7-99bf-a019bceee488.png">

**Comment by rimildeyjsr** [comment]
@stevemdixon - Hey, can I work on this?

**Comment by hamstu** [comment]
Hey @rimildeyjsr! Thanks for stopping in. 👋  I'm afraid this repo/package is being deprecated at Buffer. (Closing this now.)

**Comment by rimildeyjsr** [comment]
@hamstu - no issues! thanks! 😃
