### ISSUE TITLE
Tree Shaking

### ISSUE THREAD

**Issue by hharnisc** [bufferapp/buffer-components#2]
When we've got multiple (let's say 40) components and we only need to consume 1, how do we pull in 1 component without pulling in all 40 and bloating the code?

**Comment by casesandberg** [comment]
Webpack 2 [comes with tree-shaking](https://webpack.js.org/guides/tree-shaking/) OOTB now as long as you are using es6 import / export (which you are):
```
import { Card } from '@bufferapp/components'
```

**Comment by hharnisc** [comment]
That's awesome! Looks like it needs the `--optimize-minimize` flag added when production builds are run. Will shrink the build quite a bit :smile:

**Comment by casesandberg** [comment]
Ah yes! Alternatively, you can just use the `-p` flag which is equivalent to `--optimize-minimize --define process.env.NODE_ENV="'production'"`
