### ISSUE TITLE
Safari rendering issue on all `<Button noStyle />`

### ISSUE THREAD

**Issue by stevemdixon** [bufferapp/buffer-components#99]
All components that use the `noStyle` config of the `Button` component don't render any text in Safari when using `lineHeight: 0`. Setting `lineHeight` like this allows instances of `Button` with an `Icon` as its only child to have `Icon` perfectly center. It feels like we might need to explore an alternative solution with perhaps a last resort being a child-type specific config of `Button`.

**Comment by stevemdixon** [comment]
@hamstu has a [fix in place](https://github.com/bufferapp/buffer-components/pull/96) for this one. Perhaps we could include the solution for `<Button><Icon /></Button>` and include it in that same PR, @hharnisc?

**Comment by hharnisc** [comment]
Gonna close this one for now since there was a fix put in place for this by @hamstu! Might be worth creating another issue though for the centering for the noStyle Button
